[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["echo 'Installing .NET 8 dependencies'"]

[phases.build] 
cmds = [
  "dotnet restore ProyectoNomina.Backend/ProyectoNomina.Backend.csproj",
  "dotnet build ProyectoNomina.Backend/ProyectoNomina.Backend.csproj -c Release --no-restore",
  "dotnet publish ProyectoNomina.Backend/ProyectoNomina.Backend.csproj -c Release -o out --no-restore"
]

[start]
cmd = "cd out && dotnet ProyectoNomina.Backend.dll"

[variables]
PORT = "8080"