# Nixpacks configuration for .NET 8 deployment
[providers]
dotnet = "8.0.403"

[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "echo '=== .NET Version Info ==='",
  "dotnet --version",
  "echo '=== Current Directory ==='", 
  "pwd && ls -la",
  "echo '=== Project Files ==='",
  "find . -name '*.csproj' -type f",
  "echo '=== Restoring packages ==='",
  "dotnet restore --verbosity minimal",
  "echo '=== Publishing application ==='",
  "dotnet publish ProyectoNomina.Backend/ProyectoNomina.Backend.csproj -c Release -o ./dist --verbosity minimal"
]

[start]
cmd = "cd dist && dotnet ProyectoNomina.Backend.dll --urls http://0.0.0.0:$PORT"

[variables]
ASPNETCORE_ENVIRONMENT = "Production"