# Nixpacks configuration for .NET 8 deployment
[phases.setup]
nixPkgs = ["dotnet-sdk_8", "nodejs_18"]

[phases.build]
cmds = [
  "dotnet --version",
  "ls -la",
  "dotnet restore ProyectoNomina.Backend/ProyectoNomina.Backend.csproj --verbosity normal",
  "dotnet publish ProyectoNomina.Backend/ProyectoNomina.Backend.csproj -c Release -o ./dist --no-restore --verbosity normal"
]

[start]
cmd = "cd dist && dotnet ProyectoNomina.Backend.dll --urls http://0.0.0.0:$PORT"